# -*- coding: utf-8 -*-
"""StockMarket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_F4fBHQgZ5sxF6sqYPb_2iBaV6EgIRR
"""

stock_prices = {
    "AAPL" : 250,
    "BYD"  : 180,
    "GEMI" : 150,
    "META" : 400,
    "SPTFY": 200
}

print("----- Welcome to the StockTrader------")
print("Available stocks: ",list(stock_prices.keys()))

symbols = input("Enter the symbol for stock you want to buy (eg:AAPL): " ).upper()
quantity = int(input(f"Enter quantity of stocks you own for {symbols} : " ))


if symbols in stock_prices:
  price = stock_prices[symbols]
  total_stockval= price * quantity

  result = f"Total investment in {symbols} : ${total_stockval},price per share: {price}"
  print("\n" + result)

  with open("stockmarket.txt","w") as file:
    file.write(result)
  print("Data saved to stockmarket.txt")

else:
  print("Error , stock is not found ")